#!/bin/bash
base_dir=/opt/

#prompt on install for this info
#sudo ln -sf /etc/nginx/sites-available/$dns_name /etc/nginx/sites-enabled/$dns_name
sudo systemctl restart nginx


echo "------"
echo " create database"
source /etc/intstream/environment.conf
cd "$base_dir/intstream/backend/"
pipenv run python manage.py migrate
echo "------"
echo " create celery cache backend"
pipenv run python manage.py migrate django_celery_results
pipenv run python manage.py createcachetable

echo "------"
echo " create secret key"
pipenv run python manage.py generate_secret_key --replace 

echo "------"
echo " collect static for backend to $base_dir/intstream/backend/"
pipenv run python manage.py collectstatic

echo "------"
echo " nvm install"
sudo curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion" 
nvm install 11.6.0

echo "------"
echo " npm install"
cd "$base_dir/intstream/frontend/"
npm install

echo "------"
echo " npm build"
npm run build

#todo move file to /etc/rc.local
sudo bash -c 'cat "$0/intstream/utility/rc.local" >> /etc/rc.local' $base_dir

# pyspark requires java 1.8 
sudo apt -qq install  openjdk-8-jdk
#https://stackoverflow.com/questions/53583199/pyspark-error-unsupported-class-file-major-version-55
sudo update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java


